//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Referencias = new HashSet<Referencias>();
        }
    
        public int IdCliente { get; set; }
        public string rfc_ { get; set; }
        public string tipopersona { get; set; }
        public string matricula { get; set; }
        public string nombre_ { get; set; }
        public string apellidos { get; set; }
        public string correoelectronico { get; set; }
        public string calle { get; set; }
        public string numeroex { get; set; }
        public string numeroin { get; set; }
        public string colonia { get; set; }
        public string cp { get; set; }
        public string ciudad { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referencias> Referencias { get; set; }
    }
}
