//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBase : DbContext
    {
        public DataBase()
            : base("name=DataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArchivosBanco> ArchivosBanco { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<AreasAd> AreasAd { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Eventos> Eventos { get; set; }
        public virtual DbSet<PerfilesAd> PerfilesAd { get; set; }
        public virtual DbSet<Referencias> Referencias { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<TipoServicios> TipoServicios { get; set; }
        public virtual DbSet<UsuariosAd> UsuariosAd { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
    }
}
