//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int IdEvento { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string operacion { get; set; }
        public string descripcion { get; set; }
        public int IdUsuariosAd { get; set; }
        public string ip { get; set; }
    
        public virtual UsuariosAd UsuariosAd { get; set; }
    }
}
