//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HClientes
    {
        public int HIdCliente { get; set; }
        public int Hanio { get; set; }
        public int IdCliente { get; set; }
        public string rfc { get; set; }
        public string tipopersona { get; set; }
        public string matricula { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string correoelectronico { get; set; }
    }
}
