//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HReferencias
    {
        public int Href { get; set; }
        public int Hanio { get; set; }
        public string numref { get; set; }
        public string estadoref { get; set; }
        public System.DateTime fechaemision { get; set; }
        public System.DateTime fechaestado { get; set; }
        public System.DateTime fechavencimiento { get; set; }
        public decimal monto { get; set; }
        public int IdCliente { get; set; }
    }
}
