//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HServicios
    {
        public int Hcontro { get; set; }
        public int Hanio { get; set; }
        public int contro { get; set; }
        public string nomservicio { get; set; }
        public Nullable<decimal> costo { get; set; }
        public int cuentacontable { get; set; }
        public string nombrearea { get; set; }
        public string tipo { get; set; }
    }
}
