//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpcionesSistema
    {
        public int IdOpc { get; set; }
        public string colorPrimario { get; set; }
        public string colorPrimarioAl { get; set; }
        public string colorSecundario { get; set; }
        public string colorTitulos { get; set; }
        public string colorTexto { get; set; }
        public string colorBEliminar { get; set; }
        public string colorBEliminarAl { get; set; }
        public string colorBVer { get; set; }
        public string colorBVerAl { get; set; }
        public string colorBEditar { get; set; }
        public string colorBEditarAl { get; set; }
        public string colorBComprar { get; set; }
        public string colorBComprarAl { get; set; }
        public string numCuenta { get; set; }
        public string nomBuzon { get; set; }
        public string cuenClave { get; set; }
        public string constanteRef { get; set; }
        public string numRap { get; set; }
    }
}
