//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilesAd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PerfilesAd()
        {
            this.UsuariosAd = new HashSet<UsuariosAd>();
        }
    
        public int IdPerfil { get; set; }
        public string nombreperfil { get; set; }
        public bool adminperfiles { get; set; }
        public bool adminadareas { get; set; }
        public bool verservicios { get; set; }
        public bool admintiposervicios { get; set; }
        public bool verreferencias { get; set; }
        public bool adminusuarios { get; set; }
        public bool administrarareas { get; set; }
        public bool adminservicio { get; set; }
        public bool bitacoraeventos { get; set; }
        public bool subirarchivo { get; set; }
        public bool generarcompra { get; set; }
        public bool adminparametros { get; set; }
        public bool adminalumnos { get; set; }
        public bool veralumnos { get; set; }
        public bool subiralumnos { get; set; }
        public bool verhistorico { get; set; }
        public bool restaurarsistema { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosAd> UsuariosAd { get; set; }
    }
}
