//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicios()
        {
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int contro { get; set; }
        public int IdArea { get; set; }
        public int IdTS { get; set; }
        public string nomservicio { get; set; }
        public string Objetivo { get; set; }
        public string duracion { get; set; }
        public decimal costo { get; set; }
        public string prerrequisitos { get; set; }
        public int diasvigencia { get; set; }
        public int serviciosmaxacobrar { get; set; }
        public int cuetacontable { get; set; }
        public bool estado { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual TipoServicios TipoServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
