//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosAd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuariosAd()
        {
            this.Eventos = new HashSet<Eventos>();
        }
    
        public int IdUsuariosAd { get; set; }
        public string nombre { get; set; }
        public string iniciales { get; set; }
        public int IdPerfil { get; set; }
        public string correoelectronico { get; set; }
        public bool estado { get; set; }
        public int IdAreaAd { get; set; }
        public string contrasena { get; set; }
    
        public virtual AreasAd AreasAd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eventos> Eventos { get; set; }
        public virtual PerfilesAd PerfilesAd { get; set; }
    }
}
