//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int IdVenta { get; set; }
        public string numref { get; set; }
        public int contro { get; set; }
        public int cantidad { get; set; }
        public decimal costount { get; set; }
    
        public virtual Referencias Referencias { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
